### PR TITLE
metadata.json must have dependencies set, even if empty

### PR DESCRIPTION
**Pull request by bhourigan**
PR to address https://github.com/Nubisproject/nubis-puppet-eip/issues/10

### CODE REVIEW

**Comment by bhourigan** [comment]
It looks like the parameter passed to --query doesn't work as intended. When I run describe-stacks without --query I can get the full stack information:

``` shell
[root@ip-10-160-194-21 sbin]# aws --region us-east-1 cloudformation describe-stacks --stack-name nubis-akamai-dns
{
    "Stacks": [
        {
<...>
            "Outputs": [
                {
                    "Description": "Consul: config/ Elastic IP",
                    "OutputKey": "ElasticIP",
                    "OutputValue": "eipalloc-fef6ce9b"
                }
            ],
<...>
```

But when I run it with --query it prints an empty json template:

``` shell
[root@ip-10-160-194-21 sbin]# aws --region us-east-1 cloudformation describe-stacks --stack-name nubis-akamai-dns --query 'Stacks[].Outputs[?OutputKey == ElasticIP].OutputValue'
[
    []
]
```

I'm not familiar with --query so I went ahead and swapped it out with jq:

``` shell
[root@ip-10-160-194-21 sbin]# aws --region us-east-1 --output json cloudformation describe-stacks --stack-name nubis-akamai-dns | jq --raw-output '.Stacks[] | .Outputs[] | select(.OutputKey == "ElasticIP") | .OutputValue'
eipalloc-fef6ce9b
```

**Comment by gozer** [comment]
Yeah; very good points. And a big part of what you
mention has already been implemented in Nubis-jumphost, just not merged back in here.

@limed, can you make sure to wrap this bug up in the work to make jump host use this module?

**Comment by limed** [comment]
PR #12 invalidates this, I would double check again to see if the changes you made `eip-associate` is needed.

As for the `metadata.json` file do you mind opening a separate PR and do it on a branch so that we can merge it in cleanly. Thanks

**Comment by limed** [comment]
PR #13 and #12 invalidates this

**Pull request closed without merging**
